// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobbotfile.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlobBotFilesByBlob = `-- name: DeleteBlobBotFilesByBlob :exec
DELETE FROM blob_bot_files WHERE blob_id = $1
`

func (q *Queries) DeleteBlobBotFilesByBlob(ctx context.Context, blobID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlobBotFilesByBlob, blobID)
	return err
}

const deleteBlobBotFilesByBot = `-- name: DeleteBlobBotFilesByBot :exec
DELETE FROM blob_bot_files WHERE bot_id = $1
`

func (q *Queries) DeleteBlobBotFilesByBot(ctx context.Context, botID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlobBotFilesByBot, botID)
	return err
}

const getBlobBotFile = `-- name: GetBlobBotFile :one
SELECT blob_id, bot_id, file_id, file_unique_id, fetched_at FROM blob_bot_files WHERE blob_id = $1 AND bot_id = $2
`

type GetBlobBotFileParams struct {
	BlobID uuid.UUID
	BotID  uuid.UUID
}

func (q *Queries) GetBlobBotFile(ctx context.Context, arg GetBlobBotFileParams) (BlobBotFile, error) {
	row := q.db.QueryRow(ctx, getBlobBotFile, arg.BlobID, arg.BotID)
	var i BlobBotFile
	err := row.Scan(
		&i.BlobID,
		&i.BotID,
		&i.FileID,
		&i.FileUniqueID,
		&i.FetchedAt,
	)
	return i, err
}

const listBlobBotFilesByBlob = `-- name: ListBlobBotFilesByBlob :many
SELECT blob_id, bot_id, file_id, file_unique_id, fetched_at FROM blob_bot_files WHERE blob_id = $1
`

func (q *Queries) ListBlobBotFilesByBlob(ctx context.Context, blobID uuid.UUID) ([]BlobBotFile, error) {
	rows, err := q.db.Query(ctx, listBlobBotFilesByBlob, blobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlobBotFile
	for rows.Next() {
		var i BlobBotFile
		if err := rows.Scan(
			&i.BlobID,
			&i.BotID,
			&i.FileID,
			&i.FileUniqueID,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlobBotFile = `-- name: UpsertBlobBotFile :exec
INSERT INTO blob_bot_files (
    blob_id, bot_id, file_id, file_unique_id, fetched_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (blob_id, bot_id) DO UPDATE
SET file_id = excluded.file_id,
    file_unique_id = excluded.file_unique_id,
    fetched_at = excluded.fetched_at
`

type UpsertBlobBotFileParams struct {
	BlobID       uuid.UUID
	BotID        uuid.UUID
	FileID       string
	FileUniqueID string
	FetchedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertBlobBotFile(ctx context.Context, arg UpsertBlobBotFileParams) error {
	_, err := q.db.Exec(ctx, upsertBlobBotFile,
		arg.BlobID,
		arg.BotID,
		arg.FileID,
		arg.FileUniqueID,
		arg.FetchedAt,
	)
	return err
}
