// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blob.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBlobRefcount = `-- name: AddBlobRefcount :one
UPDATE blobs
SET refcount = refcount + $2
WHERE id = $1
RETURNING refcount
`

type AddBlobRefcountParams struct {
	ID       uuid.UUID
	Refcount int64
}

func (q *Queries) AddBlobRefcount(ctx context.Context, arg AddBlobRefcountParams) (int64, error) {
	row := q.db.QueryRow(ctx, addBlobRefcount, arg.ID, arg.Refcount)
	var refcount int64
	err := row.Scan(&refcount)
	return refcount, err
}

const addBlobRefcounts = `-- name: AddBlobRefcounts :exec
UPDATE blobs AS b
SET refcount = b.refcount + d.delta
FROM (
    SELECT
        unnest($1::uuid[])    AS id,
        unnest($2::bigint[]) AS delta
) AS d
WHERE b.id = d.id
`

type AddBlobRefcountsParams struct {
	Ids    []uuid.UUID
	Deltas []int64
}

// Applies a per-blob refcount delta in one statement. ids and deltas are
// parallel arrays (the i-th delta applies to the i-th id, which must be distinct
// and carry its already-aggregated delta). This collapses the per-extent
// AddRefcount loop (one round-trip per extent) into one round-trip per
// finalize / COPY / release.
func (q *Queries) AddBlobRefcounts(ctx context.Context, arg AddBlobRefcountsParams) error {
	_, err := q.db.Exec(ctx, addBlobRefcounts, arg.Ids, arg.Deltas)
	return err
}

const countBlobs = `-- name: CountBlobs :one
SELECT count(*) FROM blobs
`

func (q *Queries) CountBlobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlob = `-- name: CreateBlob :exec
INSERT INTO blobs (
    id, channel_id, message_id, message_seq, size, content_hash, state, refcount, created_at, sealed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateBlobParams struct {
	ID          uuid.UUID
	ChannelID   uuid.UUID
	MessageID   int64
	MessageSeq  int64
	Size        int64
	ContentHash []byte
	State       int32
	Refcount    int64
	CreatedAt   pgtype.Timestamptz
	SealedAt    pgtype.Timestamptz
}

func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) error {
	_, err := q.db.Exec(ctx, createBlob,
		arg.ID,
		arg.ChannelID,
		arg.MessageID,
		arg.MessageSeq,
		arg.Size,
		arg.ContentHash,
		arg.State,
		arg.Refcount,
		arg.CreatedAt,
		arg.SealedAt,
	)
	return err
}

const deleteBlob = `-- name: DeleteBlob :execrows
DELETE FROM blobs WHERE id = $1
`

func (q *Queries) DeleteBlob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const evictBlobsOlderThan = `-- name: EvictBlobsOlderThan :execrows
UPDATE blobs
SET state = $4
WHERE channel_id = $1 AND message_seq < $2 AND state <> $3
`

type EvictBlobsOlderThanParams struct {
	ChannelID  uuid.UUID
	MessageSeq int64
	State      int32
	State_2    int32
}

func (q *Queries) EvictBlobsOlderThan(ctx context.Context, arg EvictBlobsOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, evictBlobsOlderThan,
		arg.ChannelID,
		arg.MessageSeq,
		arg.State,
		arg.State_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlobByID = `-- name: GetBlobByID :one
SELECT id, channel_id, message_id, message_seq, size, content_hash, state, refcount, created_at, sealed_at FROM blobs WHERE id = $1
`

func (q *Queries) GetBlobByID(ctx context.Context, id uuid.UUID) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlobByID, id)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MessageID,
		&i.MessageSeq,
		&i.Size,
		&i.ContentHash,
		&i.State,
		&i.Refcount,
		&i.CreatedAt,
		&i.SealedAt,
	)
	return i, err
}

const listBlobsByChannel = `-- name: ListBlobsByChannel :many
SELECT id, channel_id, message_id, message_seq, size, content_hash, state, refcount, created_at, sealed_at FROM blobs WHERE channel_id = $1 ORDER BY message_seq
`

func (q *Queries) ListBlobsByChannel(ctx context.Context, channelID uuid.UUID) ([]Blob, error) {
	rows, err := q.db.Query(ctx, listBlobsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MessageID,
			&i.MessageSeq,
			&i.Size,
			&i.ContentHash,
			&i.State,
			&i.Refcount,
			&i.CreatedAt,
			&i.SealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlobsByState = `-- name: ListBlobsByState :many
SELECT id, channel_id, message_id, message_seq, size, content_hash, state, refcount, created_at, sealed_at FROM blobs WHERE state = $1 ORDER BY created_at
`

func (q *Queries) ListBlobsByState(ctx context.Context, state int32) ([]Blob, error) {
	rows, err := q.db.Query(ctx, listBlobsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MessageID,
			&i.MessageSeq,
			&i.Size,
			&i.ContentHash,
			&i.State,
			&i.Refcount,
			&i.CreatedAt,
			&i.SealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectableBlobs = `-- name: ListCollectableBlobs :many
SELECT id, channel_id, message_id, message_seq, size, content_hash, state, refcount, created_at, sealed_at FROM blobs
WHERE state = $1
  AND refcount <= 0
  AND created_at < now() - interval '10 minutes'
ORDER BY created_at
LIMIT $2
`

type ListCollectableBlobsParams struct {
	State int32
	Limit int32
}

func (q *Queries) ListCollectableBlobs(ctx context.Context, arg ListCollectableBlobsParams) ([]Blob, error) {
	rows, err := q.db.Query(ctx, listCollectableBlobs, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MessageID,
			&i.MessageSeq,
			&i.Size,
			&i.ContentHash,
			&i.State,
			&i.Refcount,
			&i.CreatedAt,
			&i.SealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelBlobsAvailable = `-- name: MarkChannelBlobsAvailable :exec
UPDATE blobs
SET state = $2
WHERE channel_id = $1 AND state = $3
`

type MarkChannelBlobsAvailableParams struct {
	ChannelID uuid.UUID
	State     int32
	State_2   int32
}

func (q *Queries) MarkChannelBlobsAvailable(ctx context.Context, arg MarkChannelBlobsAvailableParams) error {
	_, err := q.db.Exec(ctx, markChannelBlobsAvailable, arg.ChannelID, arg.State, arg.State_2)
	return err
}

const markChannelBlobsUnavailable = `-- name: MarkChannelBlobsUnavailable :exec
UPDATE blobs
SET state = $2
WHERE channel_id = $1 AND state <> $3
`

type MarkChannelBlobsUnavailableParams struct {
	ChannelID uuid.UUID
	State     int32
	State_2   int32
}

func (q *Queries) MarkChannelBlobsUnavailable(ctx context.Context, arg MarkChannelBlobsUnavailableParams) error {
	_, err := q.db.Exec(ctx, markChannelBlobsUnavailable, arg.ChannelID, arg.State, arg.State_2)
	return err
}

const setBlobState = `-- name: SetBlobState :execrows
UPDATE blobs SET state = $2 WHERE id = $1
`

type SetBlobStateParams struct {
	ID    uuid.UUID
	State int32
}

func (q *Queries) SetBlobState(ctx context.Context, arg SetBlobStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBlobState, arg.ID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBlob = `-- name: UpdateBlob :execrows
UPDATE blobs
SET channel_id = $2,
    message_id = $3,
    message_seq = $4,
    size = $5,
    state = $6,
    refcount = $7,
    sealed_at = $8
WHERE id = $1
`

type UpdateBlobParams struct {
	ID         uuid.UUID
	ChannelID  uuid.UUID
	MessageID  int64
	MessageSeq int64
	Size       int64
	State      int32
	Refcount   int64
	SealedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateBlob(ctx context.Context, arg UpdateBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBlob,
		arg.ID,
		arg.ChannelID,
		arg.MessageID,
		arg.MessageSeq,
		arg.Size,
		arg.State,
		arg.Refcount,
		arg.SealedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
