// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBot = `-- name: CreateBot :exec
INSERT INTO bots (
    id, username, token_sha, token_enc, enabled, unavailable_until, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateBotParams struct {
	ID               uuid.UUID
	Username         string
	TokenSha         string
	TokenEnc         []byte
	Enabled          bool
	UnavailableUntil pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) error {
	_, err := q.db.Exec(ctx, createBot,
		arg.ID,
		arg.Username,
		arg.TokenSha,
		arg.TokenEnc,
		arg.Enabled,
		arg.UnavailableUntil,
		arg.CreatedAt,
	)
	return err
}

const deleteBot = `-- name: DeleteBot :execrows
DELETE FROM bots WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, username, token_sha, token_enc, enabled, unavailable_until, created_at FROM bots WHERE id = $1
`

func (q *Queries) GetBotByID(ctx context.Context, id uuid.UUID) (Bot, error) {
	row := q.db.QueryRow(ctx, getBotByID, id)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TokenSha,
		&i.TokenEnc,
		&i.Enabled,
		&i.UnavailableUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getBotByUsername = `-- name: GetBotByUsername :one
SELECT id, username, token_sha, token_enc, enabled, unavailable_until, created_at FROM bots WHERE username = $1
`

func (q *Queries) GetBotByUsername(ctx context.Context, username string) (Bot, error) {
	row := q.db.QueryRow(ctx, getBotByUsername, username)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TokenSha,
		&i.TokenEnc,
		&i.Enabled,
		&i.UnavailableUntil,
		&i.CreatedAt,
	)
	return i, err
}

const listBots = `-- name: ListBots :many
SELECT id, username, token_sha, token_enc, enabled, unavailable_until, created_at FROM bots ORDER BY created_at
`

func (q *Queries) ListBots(ctx context.Context) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TokenSha,
			&i.TokenEnc,
			&i.Enabled,
			&i.UnavailableUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotsByIDs = `-- name: ListBotsByIDs :many
SELECT id, username, token_sha, token_enc, enabled, unavailable_until, created_at FROM bots WHERE id = ANY($1::uuid[])
`

// Batch load bots by id (one round-trip instead of GetByID per member bot on the
// blob read candidate path).
func (q *Queries) ListBotsByIDs(ctx context.Context, ids []uuid.UUID) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listBotsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TokenSha,
			&i.TokenEnc,
			&i.Enabled,
			&i.UnavailableUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBotUnavailableUntil = `-- name: SetBotUnavailableUntil :execrows
UPDATE bots SET unavailable_until = $2 WHERE id = $1
`

type SetBotUnavailableUntilParams struct {
	ID               uuid.UUID
	UnavailableUntil pgtype.Timestamptz
}

func (q *Queries) SetBotUnavailableUntil(ctx context.Context, arg SetBotUnavailableUntilParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBotUnavailableUntil, arg.ID, arg.UnavailableUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBot = `-- name: UpdateBot :execrows
UPDATE bots
SET username = $2,
    token_sha = $3,
    token_enc = $4,
    enabled = $5,
    unavailable_until = $6
WHERE id = $1
`

type UpdateBotParams struct {
	ID               uuid.UUID
	Username         string
	TokenSha         string
	TokenEnc         []byte
	Enabled          bool
	UnavailableUntil pgtype.Timestamptz
}

func (q *Queries) UpdateBot(ctx context.Context, arg UpdateBotParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBot,
		arg.ID,
		arg.Username,
		arg.TokenSha,
		arg.TokenEnc,
		arg.Enabled,
		arg.UnavailableUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
