// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: botchannel.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBotChannelsByBot = `-- name: DeleteBotChannelsByBot :exec
DELETE FROM bot_channel WHERE bot_id = $1
`

func (q *Queries) DeleteBotChannelsByBot(ctx context.Context, botID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotChannelsByBot, botID)
	return err
}

const deleteBotChannelsByChannel = `-- name: DeleteBotChannelsByChannel :exec
DELETE FROM bot_channel WHERE channel_id = $1
`

func (q *Queries) DeleteBotChannelsByChannel(ctx context.Context, channelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotChannelsByChannel, channelID)
	return err
}

const getBotChannel = `-- name: GetBotChannel :one
SELECT bot_id, channel_id, member, checked_at FROM bot_channel WHERE bot_id = $1 AND channel_id = $2
`

type GetBotChannelParams struct {
	BotID     uuid.UUID
	ChannelID uuid.UUID
}

func (q *Queries) GetBotChannel(ctx context.Context, arg GetBotChannelParams) (BotChannel, error) {
	row := q.db.QueryRow(ctx, getBotChannel, arg.BotID, arg.ChannelID)
	var i BotChannel
	err := row.Scan(
		&i.BotID,
		&i.ChannelID,
		&i.Member,
		&i.CheckedAt,
	)
	return i, err
}

const listBotChannelsByBot = `-- name: ListBotChannelsByBot :many
SELECT bot_id, channel_id, member, checked_at FROM bot_channel WHERE bot_id = $1
`

func (q *Queries) ListBotChannelsByBot(ctx context.Context, botID uuid.UUID) ([]BotChannel, error) {
	rows, err := q.db.Query(ctx, listBotChannelsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotChannel
	for rows.Next() {
		var i BotChannel
		if err := rows.Scan(
			&i.BotID,
			&i.ChannelID,
			&i.Member,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotChannelsByChannel = `-- name: ListBotChannelsByChannel :many
SELECT bot_id, channel_id, member, checked_at FROM bot_channel WHERE channel_id = $1
`

func (q *Queries) ListBotChannelsByChannel(ctx context.Context, channelID uuid.UUID) ([]BotChannel, error) {
	rows, err := q.db.Query(ctx, listBotChannelsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotChannel
	for rows.Next() {
		var i BotChannel
		if err := rows.Scan(
			&i.BotID,
			&i.ChannelID,
			&i.Member,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotChannel = `-- name: UpsertBotChannel :exec
INSERT INTO bot_channel (
    bot_id, channel_id, member, checked_at
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (bot_id, channel_id) DO UPDATE
SET member = excluded.member,
    checked_at = excluded.checked_at
`

type UpsertBotChannelParams struct {
	BotID     uuid.UUID
	ChannelID uuid.UUID
	Member    bool
	CheckedAt pgtype.Timestamptz
}

func (q *Queries) UpsertBotChannel(ctx context.Context, arg UpsertBotChannelParams) error {
	_, err := q.db.Exec(ctx, upsertBotChannel,
		arg.BotID,
		arg.ChannelID,
		arg.Member,
		arg.CheckedAt,
	)
	return err
}
