// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (
    id, tg_chat_id, title, message_counter, eviction_threshold, available, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateChannelParams struct {
	ID                uuid.UUID
	TgChatID          int64
	Title             string
	MessageCounter    int64
	EvictionThreshold int64
	Available         bool
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.Exec(ctx, createChannel,
		arg.ID,
		arg.TgChatID,
		arg.Title,
		arg.MessageCounter,
		arg.EvictionThreshold,
		arg.Available,
		arg.CreatedAt,
	)
	return err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelByChatID = `-- name: GetChannelByChatID :one
SELECT id, tg_chat_id, title, message_counter, eviction_threshold, available, created_at FROM channels WHERE tg_chat_id = $1
`

func (q *Queries) GetChannelByChatID(ctx context.Context, tgChatID int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByChatID, tgChatID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TgChatID,
		&i.Title,
		&i.MessageCounter,
		&i.EvictionThreshold,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, tg_chat_id, title, message_counter, eviction_threshold, available, created_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TgChatID,
		&i.Title,
		&i.MessageCounter,
		&i.EvictionThreshold,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}

const incrementChannelCounter = `-- name: IncrementChannelCounter :one
UPDATE channels
SET message_counter = message_counter + $2
WHERE id = $1
RETURNING message_counter
`

type IncrementChannelCounterParams struct {
	ID             uuid.UUID
	MessageCounter int64
}

func (q *Queries) IncrementChannelCounter(ctx context.Context, arg IncrementChannelCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementChannelCounter, arg.ID, arg.MessageCounter)
	var message_counter int64
	err := row.Scan(&message_counter)
	return message_counter, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, tg_chat_id, title, message_counter, eviction_threshold, available, created_at FROM channels ORDER BY created_at
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.TgChatID,
			&i.Title,
			&i.MessageCounter,
			&i.EvictionThreshold,
			&i.Available,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelAvailable = `-- name: SetChannelAvailable :execrows
UPDATE channels SET available = $2 WHERE id = $1
`

type SetChannelAvailableParams struct {
	ID        uuid.UUID
	Available bool
}

func (q *Queries) SetChannelAvailable(ctx context.Context, arg SetChannelAvailableParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelAvailable, arg.ID, arg.Available)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannel = `-- name: UpdateChannel :execrows
UPDATE channels
SET tg_chat_id = $2,
    title = $3,
    message_counter = $4,
    eviction_threshold = $5,
    available = $6
WHERE id = $1
`

type UpdateChannelParams struct {
	ID                uuid.UUID
	TgChatID          int64
	Title             string
	MessageCounter    int64
	EvictionThreshold int64
	Available         bool
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannel,
		arg.ID,
		arg.TgChatID,
		arg.Title,
		arg.MessageCounter,
		arg.EvictionThreshold,
		arg.Available,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
