// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateExtents implements pgx.CopyFromSource.
type iteratorForCreateExtents struct {
	rows                 []CreateExtentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateExtents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateExtents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].NodeID,
		r.rows[0].Seq,
		r.rows[0].FileOffset,
		r.rows[0].Length,
		r.rows[0].BlobID,
		r.rows[0].BlobOffset,
	}, nil
}

func (r iteratorForCreateExtents) Err() error {
	return nil
}

func (q *Queries) CreateExtents(ctx context.Context, arg []CreateExtentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"extents"}, []string{"id", "node_id", "seq", "file_offset", "length", "blob_id", "blob_offset"}, &iteratorForCreateExtents{rows: arg})
}
