// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events
WHERE ($1::text = '' OR kind = $1::text)
`

func (q *Queries) CountEvents(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, ts, kind, message, ref FROM events
WHERE ($1::text = '' OR kind = $1::text)
ORDER BY ts DESC
LIMIT $3::int
OFFSET $2::int
`

type ListEventsParams struct {
	Kind      string
	RowOffset *int32
	RowLimit  *int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Kind, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Message,
			&i.Ref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logEvent = `-- name: LogEvent :exec
INSERT INTO events (
    id, ts, kind, message, ref
) VALUES (
    $1, $2, $3, $4, $5
)
`

type LogEventParams struct {
	ID      uuid.UUID
	Ts      pgtype.Timestamptz
	Kind    string
	Message string
	Ref     string
}

func (q *Queries) LogEvent(ctx context.Context, arg LogEventParams) error {
	_, err := q.db.Exec(ctx, logEvent,
		arg.ID,
		arg.Ts,
		arg.Kind,
		arg.Message,
		arg.Ref,
	)
	return err
}
