// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extent.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const copyExtentsForNode = `-- name: CopyExtentsForNode :exec
INSERT INTO extents (id, node_id, seq, file_offset, length, blob_id, blob_offset)
SELECT gen_random_uuid(), $1, src.seq, src.file_offset, src.length, src.blob_id, src.blob_offset
FROM extents src
WHERE src.node_id = $2
`

type CopyExtentsForNodeParams struct {
	NodeID   uuid.UUID
	NodeID_2 uuid.UUID
}

func (q *Queries) CopyExtentsForNode(ctx context.Context, arg CopyExtentsForNodeParams) error {
	_, err := q.db.Exec(ctx, copyExtentsForNode, arg.NodeID, arg.NodeID_2)
	return err
}

type CreateExtentsParams struct {
	ID         uuid.UUID
	NodeID     uuid.UUID
	Seq        int64
	FileOffset int64
	Length     int64
	BlobID     uuid.UUID
	BlobOffset int64
}

const deleteExtentsByNode = `-- name: DeleteExtentsByNode :exec
DELETE FROM extents WHERE node_id = $1
`

func (q *Queries) DeleteExtentsByNode(ctx context.Context, nodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExtentsByNode, nodeID)
	return err
}

const listBlobIDsByNode = `-- name: ListBlobIDsByNode :many
SELECT DISTINCT blob_id FROM extents WHERE node_id = $1
`

func (q *Queries) ListBlobIDsByNode(ctx context.Context, nodeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBlobIDsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var blob_id uuid.UUID
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtentsByNode = `-- name: ListExtentsByNode :many
SELECT id, node_id, seq, file_offset, length, blob_id, blob_offset FROM extents WHERE node_id = $1 ORDER BY seq
`

func (q *Queries) ListExtentsByNode(ctx context.Context, nodeID uuid.UUID) ([]Extent, error) {
	rows, err := q.db.Query(ctx, listExtentsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Extent
	for rows.Next() {
		var i Extent
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Seq,
			&i.FileOffset,
			&i.Length,
			&i.BlobID,
			&i.BlobOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesSolelyOnBlob = `-- name: ListNodesSolelyOnBlob :many
SELECT node_id
FROM extents
GROUP BY node_id
HAVING bool_and(blob_id = $1)
`

func (q *Queries) ListNodesSolelyOnBlob(ctx context.Context, blobID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listNodesSolelyOnBlob, blobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var node_id uuid.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
