// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	Name       string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type Blob struct {
	ID          uuid.UUID
	ChannelID   uuid.UUID
	MessageID   int64
	MessageSeq  int64
	Size        int64
	ContentHash []byte
	State       int32
	Refcount    int64
	CreatedAt   pgtype.Timestamptz
	SealedAt    pgtype.Timestamptz
}

type BlobBotFile struct {
	BlobID       uuid.UUID
	BotID        uuid.UUID
	FileID       string
	FileUniqueID string
	FetchedAt    pgtype.Timestamptz
}

type Bot struct {
	ID               uuid.UUID
	Username         string
	TokenSha         string
	TokenEnc         []byte
	Enabled          bool
	UnavailableUntil pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type BotChannel struct {
	BotID     uuid.UUID
	ChannelID uuid.UUID
	Member    bool
	CheckedAt pgtype.Timestamptz
}

type Channel struct {
	ID                uuid.UUID
	TgChatID          int64
	Title             string
	MessageCounter    int64
	EvictionThreshold int64
	Available         bool
	CreatedAt         pgtype.Timestamptz
}

type Event struct {
	ID      uuid.UUID
	Ts      pgtype.Timestamptz
	Kind    string
	Message string
	Ref     string
}

type Extent struct {
	ID         uuid.UUID
	NodeID     uuid.UUID
	Seq        int64
	FileOffset int64
	Length     int64
	BlobID     uuid.UUID
	BlobOffset int64
}

type Node struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	ParentID         pgtype.UUID
	Name             string
	Path             string
	IsDir            bool
	Size             int64
	ContentHash      string
	Etag             string
	ContentType      string
	State            int32
	PackerLeaseOwner string
	PackerLeaseUntil pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	ModifiedAt       pgtype.Timestamptz
}

type SchemaMigration struct {
	Version string
}

type Setting struct {
	ID                       int32
	BlobMaxSize              int64
	WalIdleTimeoutMs         int64
	MaxFileSize              int64
	DefaultEvictionThreshold int64
	UpdatedAt                pgtype.Timestamptz
}

type StatSample struct {
	ID     uuid.UUID
	Ts     pgtype.Timestamptz
	Metric string
	Label  string
	Value  float64
}

type User struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	IsAdmin      bool
	QuotaBytes   int64
	BandwidthBps int64
	RatePerMin   int32
	CreatedAt    pgtype.Timestamptz
}

type WalChunk struct {
	ID        uuid.UUID
	NodeID    uuid.UUID
	Seq       int64
	Data      []byte
	CreatedAt pgtype.Timestamptz
}
