// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimBufferedForPacking = `-- name: ClaimBufferedForPacking :many
UPDATE nodes
SET packer_lease_owner = $1, packer_lease_until = $2
WHERE id IN (
    SELECT id FROM nodes
    WHERE state = 1
      AND (packer_lease_until IS NULL OR packer_lease_until < now())
    ORDER BY modified_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, parent_id, name, path, is_dir, size, content_hash, etag, content_type, state, packer_lease_owner, packer_lease_until, created_at, modified_at
`

type ClaimBufferedForPackingParams struct {
	PackerLeaseOwner string
	PackerLeaseUntil pgtype.Timestamptz
	Limit            int32
}

func (q *Queries) ClaimBufferedForPacking(ctx context.Context, arg ClaimBufferedForPackingParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, claimBufferedForPacking, arg.PackerLeaseOwner, arg.PackerLeaseUntil, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.Etag,
			&i.ContentType,
			&i.State,
			&i.PackerLeaseOwner,
			&i.PackerLeaseUntil,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChildren = `-- name: CountChildren :one
SELECT count(*) FROM nodes WHERE parent_id = $1
`

func (q *Queries) CountChildren(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
    id, user_id, parent_id, name, path, is_dir, size,
    content_hash, etag, content_type, state, created_at, modified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
`

type CreateNodeParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ParentID    pgtype.UUID
	Name        string
	Path        string
	IsDir       bool
	Size        int64
	ContentHash string
	Etag        string
	ContentType string
	State       int32
	CreatedAt   pgtype.Timestamptz
	ModifiedAt  pgtype.Timestamptz
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.Exec(ctx, createNode,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.Path,
		arg.IsDir,
		arg.Size,
		arg.ContentHash,
		arg.Etag,
		arg.ContentType,
		arg.State,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	return err
}

const deleteNode = `-- name: DeleteNode :execrows
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, user_id, parent_id, name, path, is_dir, size, content_hash, etag, content_type, state, packer_lease_owner, packer_lease_until, created_at, modified_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.Etag,
		&i.ContentType,
		&i.State,
		&i.PackerLeaseOwner,
		&i.PackerLeaseUntil,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getNodeByPath = `-- name: GetNodeByPath :one
SELECT id, user_id, parent_id, name, path, is_dir, size, content_hash, etag, content_type, state, packer_lease_owner, packer_lease_until, created_at, modified_at FROM nodes WHERE user_id = $1 AND path = $2
`

type GetNodeByPathParams struct {
	UserID uuid.UUID
	Path   string
}

func (q *Queries) GetNodeByPath(ctx context.Context, arg GetNodeByPathParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByPath, arg.UserID, arg.Path)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.Etag,
		&i.ContentType,
		&i.State,
		&i.PackerLeaseOwner,
		&i.PackerLeaseUntil,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listChildren = `-- name: ListChildren :many
SELECT id, user_id, parent_id, name, path, is_dir, size, content_hash, etag, content_type, state, packer_lease_owner, packer_lease_until, created_at, modified_at FROM nodes
WHERE user_id = $1 AND parent_id = $2
ORDER BY name
`

type ListChildrenParams struct {
	UserID   uuid.UUID
	ParentID pgtype.UUID
}

func (q *Queries) ListChildren(ctx context.Context, arg ListChildrenParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listChildren, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.Etag,
			&i.ContentType,
			&i.State,
			&i.PackerLeaseOwner,
			&i.PackerLeaseUntil,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtree = `-- name: ListSubtree :many
SELECT id, user_id, parent_id, name, path, is_dir, size, content_hash, etag, content_type, state, packer_lease_owner, packer_lease_until, created_at, modified_at FROM nodes
WHERE user_id = $1 AND (path = $2 OR path LIKE $3 ESCAPE '\')
ORDER BY path
`

type ListSubtreeParams struct {
	UserID     uuid.UUID
	Path       string
	LikeEscape []byte
}

func (q *Queries) ListSubtree(ctx context.Context, arg ListSubtreeParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listSubtree, arg.UserID, arg.Path, arg.LikeEscape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.Etag,
			&i.ContentType,
			&i.State,
			&i.PackerLeaseOwner,
			&i.PackerLeaseUntil,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoredIfOwner = `-- name: MarkStoredIfOwner :one
UPDATE nodes
SET state = 2, packer_lease_owner = '', packer_lease_until = NULL
WHERE id = $1 AND state = 1 AND packer_lease_owner = $2
RETURNING id
`

type MarkStoredIfOwnerParams struct {
	ID               uuid.UUID
	PackerLeaseOwner string
}

func (q *Queries) MarkStoredIfOwner(ctx context.Context, arg MarkStoredIfOwnerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markStoredIfOwner, arg.ID, arg.PackerLeaseOwner)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const releaseLease = `-- name: ReleaseLease :execrows
UPDATE nodes
SET packer_lease_owner = '', packer_lease_until = NULL
WHERE id = $1
`

func (q *Queries) ReleaseLease(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseLease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumSizeByUser = `-- name: SumSizeByUser :one
SELECT COALESCE(SUM(size), 0)::bigint FROM nodes
WHERE user_id = $1 AND is_dir = false
`

func (q *Queries) SumSizeByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumSizeByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateNode = `-- name: UpdateNode :execrows
UPDATE nodes
SET parent_id = $2,
    name = $3,
    path = $4,
    is_dir = $5,
    size = $6,
    content_hash = $7,
    etag = $8,
    content_type = $9,
    state = $10,
    modified_at = $11
WHERE id = $1
`

type UpdateNodeParams struct {
	ID          uuid.UUID
	ParentID    pgtype.UUID
	Name        string
	Path        string
	IsDir       bool
	Size        int64
	ContentHash string
	Etag        string
	ContentType string
	State       int32
	ModifiedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNode,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Path,
		arg.IsDir,
		arg.Size,
		arg.ContentHash,
		arg.Etag,
		arg.ContentType,
		arg.State,
		arg.ModifiedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
