// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettings = `-- name: GetSettings :one
SELECT id, blob_max_size, wal_idle_timeout_ms, max_file_size, default_eviction_threshold, updated_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.BlobMaxSize,
		&i.WalIdleTimeoutMs,
		&i.MaxFileSize,
		&i.DefaultEvictionThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO settings (
    id, blob_max_size, wal_idle_timeout_ms, max_file_size, default_eviction_threshold, updated_at
) VALUES (
    1, $1, $2, $3, $4, $5
)
ON CONFLICT (id) DO UPDATE
SET blob_max_size = excluded.blob_max_size,
    wal_idle_timeout_ms = excluded.wal_idle_timeout_ms,
    max_file_size = excluded.max_file_size,
    default_eviction_threshold = excluded.default_eviction_threshold,
    updated_at = excluded.updated_at
`

type UpsertSettingsParams struct {
	BlobMaxSize              int64
	WalIdleTimeoutMs         int64
	MaxFileSize              int64
	DefaultEvictionThreshold int64
	UpdatedAt                pgtype.Timestamptz
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertSettings,
		arg.BlobMaxSize,
		arg.WalIdleTimeoutMs,
		arg.MaxFileSize,
		arg.DefaultEvictionThreshold,
		arg.UpdatedAt,
	)
	return err
}
