// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stat.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const latestStat = `-- name: LatestStat :one
SELECT id, ts, metric, label, value FROM stat_samples
WHERE metric = $1 AND label = $2
ORDER BY ts DESC
LIMIT 1
`

type LatestStatParams struct {
	Metric string
	Label  string
}

func (q *Queries) LatestStat(ctx context.Context, arg LatestStatParams) (StatSample, error) {
	row := q.db.QueryRow(ctx, latestStat, arg.Metric, arg.Label)
	var i StatSample
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Metric,
		&i.Label,
		&i.Value,
	)
	return i, err
}

const queryStats = `-- name: QueryStats :many
SELECT id, ts, metric, label, value FROM stat_samples
WHERE metric = $1 AND label = $2 AND ts >= $3 AND ts <= $4
ORDER BY ts
`

type QueryStatsParams struct {
	Metric string
	Label  string
	Ts     pgtype.Timestamptz
	Ts_2   pgtype.Timestamptz
}

func (q *Queries) QueryStats(ctx context.Context, arg QueryStatsParams) ([]StatSample, error) {
	rows, err := q.db.Query(ctx, queryStats,
		arg.Metric,
		arg.Label,
		arg.Ts,
		arg.Ts_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatSample
	for rows.Next() {
		var i StatSample
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Metric,
			&i.Label,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStat = `-- name: RecordStat :exec
INSERT INTO stat_samples (
    id, ts, metric, label, value
) VALUES (
    $1, $2, $3, $4, $5
)
`

type RecordStatParams struct {
	ID     uuid.UUID
	Ts     pgtype.Timestamptz
	Metric string
	Label  string
	Value  float64
}

func (q *Queries) RecordStat(ctx context.Context, arg RecordStatParams) error {
	_, err := q.db.Exec(ctx, recordStat,
		arg.ID,
		arg.Ts,
		arg.Metric,
		arg.Label,
		arg.Value,
	)
	return err
}
