// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, login, password_hash, is_admin, quota_bytes, bandwidth_bps, rate_per_min, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	IsAdmin      bool
	QuotaBytes   int64
	BandwidthBps int64
	RatePerMin   int32
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.QuotaBytes,
		arg.BandwidthBps,
		arg.RatePerMin,
		arg.CreatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, password_hash, is_admin, quota_bytes, bandwidth_bps, rate_per_min, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.QuotaBytes,
		&i.BandwidthBps,
		&i.RatePerMin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash, is_admin, quota_bytes, bandwidth_bps, rate_per_min, created_at FROM users WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.QuotaBytes,
		&i.BandwidthBps,
		&i.RatePerMin,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, password_hash, is_admin, quota_bytes, bandwidth_bps, rate_per_min, created_at FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.QuotaBytes,
			&i.BandwidthBps,
			&i.RatePerMin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET login = $2,
    password_hash = $3,
    is_admin = $4,
    quota_bytes = $5,
    bandwidth_bps = $6,
    rate_per_min = $7
WHERE id = $1
`

type UpdateUserParams struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	IsAdmin      bool
	QuotaBytes   int64
	BandwidthBps int64
	RatePerMin   int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.QuotaBytes,
		arg.BandwidthBps,
		arg.RatePerMin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
