// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wal.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendWALChunk = `-- name: AppendWALChunk :exec
INSERT INTO wal_chunks (
    id, node_id, seq, data, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type AppendWALChunkParams struct {
	ID        uuid.UUID
	NodeID    uuid.UUID
	Seq       int64
	Data      []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AppendWALChunk(ctx context.Context, arg AppendWALChunkParams) error {
	_, err := q.db.Exec(ctx, appendWALChunk,
		arg.ID,
		arg.NodeID,
		arg.Seq,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const deleteWALChunksByNode = `-- name: DeleteWALChunksByNode :exec
DELETE FROM wal_chunks WHERE node_id = $1
`

func (q *Queries) DeleteWALChunksByNode(ctx context.Context, nodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWALChunksByNode, nodeID)
	return err
}

const listWALChunksByNode = `-- name: ListWALChunksByNode :many
SELECT id, node_id, seq, data, created_at FROM wal_chunks WHERE node_id = $1 ORDER BY seq
`

func (q *Queries) ListWALChunksByNode(ctx context.Context, nodeID uuid.UUID) ([]WalChunk, error) {
	rows, err := q.db.Query(ctx, listWALChunksByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalChunk
	for rows.Next() {
		var i WalChunk
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Seq,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wALSizeByNode = `-- name: WALSizeByNode :one
SELECT COALESCE(SUM(octet_length(data)), 0)::bigint FROM wal_chunks
WHERE node_id = $1
`

func (q *Queries) WALSizeByNode(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, wALSizeByNode, nodeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
