// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package model

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// BlobStateOpen is a BlobState of type Open.
	BlobStateOpen BlobState = iota
	// BlobStateSealed is a BlobState of type Sealed.
	BlobStateSealed
	// BlobStateUploading is a BlobState of type Uploading.
	BlobStateUploading
	// BlobStateStored is a BlobState of type Stored.
	BlobStateStored
	// BlobStateUnavailable is a BlobState of type Unavailable.
	BlobStateUnavailable
	// BlobStatePermUnavailable is a BlobState of type Perm_unavailable.
	BlobStatePermUnavailable
)

var ErrInvalidBlobState = errors.New("not a valid BlobState")

const _BlobStateName = "opensealeduploadingstoredunavailableperm_unavailable"

// BlobStateValues returns a list of the values for BlobState
func BlobStateValues() []BlobState {
	return []BlobState{
		BlobStateOpen,
		BlobStateSealed,
		BlobStateUploading,
		BlobStateStored,
		BlobStateUnavailable,
		BlobStatePermUnavailable,
	}
}

var _BlobStateMap = map[BlobState]string{
	BlobStateOpen:            _BlobStateName[0:4],
	BlobStateSealed:          _BlobStateName[4:10],
	BlobStateUploading:       _BlobStateName[10:19],
	BlobStateStored:          _BlobStateName[19:25],
	BlobStateUnavailable:     _BlobStateName[25:36],
	BlobStatePermUnavailable: _BlobStateName[36:52],
}

// String implements the Stringer interface.
func (x BlobState) String() string {
	if str, ok := _BlobStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("BlobState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BlobState) IsValid() bool {
	_, ok := _BlobStateMap[x]
	return ok
}

var _BlobStateValue = map[string]BlobState{
	_BlobStateName[0:4]:   BlobStateOpen,
	_BlobStateName[4:10]:  BlobStateSealed,
	_BlobStateName[10:19]: BlobStateUploading,
	_BlobStateName[19:25]: BlobStateStored,
	_BlobStateName[25:36]: BlobStateUnavailable,
	_BlobStateName[36:52]: BlobStatePermUnavailable,
}

// ParseBlobState attempts to convert a string to a BlobState.
func ParseBlobState(name string) (BlobState, error) {
	if x, ok := _BlobStateValue[name]; ok {
		return x, nil
	}
	return BlobState(0), fmt.Errorf("%s is %w", name, ErrInvalidBlobState)
}

var errBlobStateNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *BlobState) Scan(value interface{}) (err error) {
	if value == nil {
		*x = BlobState(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = BlobState(v)
	case string:
		*x, err = ParseBlobState(v)
	case []byte:
		*x, err = ParseBlobState(string(v))
	case BlobState:
		*x = v
	case int:
		*x = BlobState(v)
	case *BlobState:
		if v == nil {
			return errBlobStateNilPtr
		}
		*x = *v
	case uint:
		*x = BlobState(v)
	case uint64:
		*x = BlobState(v)
	case *int:
		if v == nil {
			return errBlobStateNilPtr
		}
		*x = BlobState(*v)
	case *int64:
		if v == nil {
			return errBlobStateNilPtr
		}
		*x = BlobState(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = BlobState(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errBlobStateNilPtr
		}
		*x = BlobState(*v)
	case *uint:
		if v == nil {
			return errBlobStateNilPtr
		}
		*x = BlobState(*v)
	case *uint64:
		if v == nil {
			return errBlobStateNilPtr
		}
		*x = BlobState(*v)
	case *string:
		if v == nil {
			return errBlobStateNilPtr
		}
		*x, err = ParseBlobState(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x BlobState) Value() (driver.Value, error) {
	return x.String(), nil
}
