// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// NodeStateWriting is a NodeState of type Writing.
	NodeStateWriting NodeState = iota
	// NodeStateBuffered is a NodeState of type Buffered.
	NodeStateBuffered
	// NodeStateStored is a NodeState of type Stored.
	NodeStateStored
)

var ErrInvalidNodeState = errors.New("not a valid NodeState")

const _NodeStateName = "writingbufferedstored"

// NodeStateValues returns a list of the values for NodeState
func NodeStateValues() []NodeState {
	return []NodeState{
		NodeStateWriting,
		NodeStateBuffered,
		NodeStateStored,
	}
}

var _NodeStateMap = map[NodeState]string{
	NodeStateWriting:  _NodeStateName[0:7],
	NodeStateBuffered: _NodeStateName[7:15],
	NodeStateStored:   _NodeStateName[15:21],
}

// String implements the Stringer interface.
func (x NodeState) String() string {
	if str, ok := _NodeStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("NodeState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NodeState) IsValid() bool {
	_, ok := _NodeStateMap[x]
	return ok
}

var _NodeStateValue = map[string]NodeState{
	_NodeStateName[0:7]:   NodeStateWriting,
	_NodeStateName[7:15]:  NodeStateBuffered,
	_NodeStateName[15:21]: NodeStateStored,
}

// ParseNodeState attempts to convert a string to a NodeState.
func ParseNodeState(name string) (NodeState, error) {
	if x, ok := _NodeStateValue[name]; ok {
		return x, nil
	}
	return NodeState(0), fmt.Errorf("%s is %w", name, ErrInvalidNodeState)
}
