//go:build go1.22

// Package management provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package management

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// APIToken defines model for APIToken.
type APIToken struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	LastUsedAt *time.Time         `json:"last_used_at"`
	Name       string             `json:"name"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// AddBot defines model for AddBot.
type AddBot struct {
	// Token The Telegram Bot API token.
	Token string `json:"token"`
}

// AddChannel defines model for AddChannel.
type AddChannel struct {
	// BareId The bare channel id (the -100 prefix is applied internally).
	BareId int64 `json:"bare_id"`
}

// Bot defines model for Bot.
type Bot struct {
	CreatedAt        time.Time          `json:"created_at"`
	Enabled          bool               `json:"enabled"`
	Id               openapi_types.UUID `json:"id"`
	UnavailableUntil *time.Time         `json:"unavailable_until"`
	Username         string             `json:"username"`
}

// Channel defines model for Channel.
type Channel struct {
	Available         bool               `json:"available"`
	CreatedAt         time.Time          `json:"created_at"`
	EvictionThreshold int64              `json:"eviction_threshold"`
	Id                openapi_types.UUID `json:"id"`
	MessageCounter    int64              `json:"message_counter"`
	TgChatId          int64              `json:"tg_chat_id"`
	Title             string             `json:"title"`
}

// CreateToken defines model for CreateToken.
type CreateToken struct {
	Name string `json:"name"`
}

// CreateUser defines model for CreateUser.
type CreateUser struct {
	BandwidthBps *int64 `json:"bandwidth_bps,omitempty"`
	IsAdmin      *bool  `json:"is_admin,omitempty"`
	Login        string `json:"login"`
	Password     string `json:"password"`
	QuotaBytes   *int64 `json:"quota_bytes,omitempty"`
	RatePerMin   *int32 `json:"rate_per_min,omitempty"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`

	// Token The plaintext bearer token, returned exactly once.
	Token  string             `json:"token"`
	UserId openapi_types.UUID `json:"user_id"`
}

// Error defines model for Error.
type Error struct {
	// Error A human-readable error message.
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Id      openapi_types.UUID `json:"id"`
	Kind    string             `json:"kind"`
	Message string             `json:"message"`
	Ref     string             `json:"ref"`
	Ts      time.Time          `json:"ts"`
}

// EventPage defines model for EventPage.
type EventPage struct {
	Events []Event `json:"events"`
	Total  int64   `json:"total"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// SetEnabled defines model for SetEnabled.
type SetEnabled struct {
	Enabled bool `json:"enabled"`
}

// SetEviction defines model for SetEviction.
type SetEviction struct {
	Threshold int64 `json:"threshold"`
}

// SetPassword defines model for SetPassword.
type SetPassword struct {
	Password string `json:"password"`
}

// Settings defines model for Settings.
type Settings struct {
	// BlobMaxSize Working blob size in bytes.
	BlobMaxSize int64 `json:"blob_max_size"`

	// DefaultEvictionThreshold Eviction threshold seeded onto new channels.
	DefaultEvictionThreshold int64 `json:"default_eviction_threshold"`

	// MaxFileSize Maximum single uploaded file size in bytes (0 = unlimited).
	MaxFileSize int64     `json:"max_file_size"`
	UpdatedAt   time.Time `json:"updated_at"`

	// WalIdleTimeoutMs WAL idle flush timeout in milliseconds.
	WalIdleTimeoutMs int64 `json:"wal_idle_timeout_ms"`
}

// StatPoint defines model for StatPoint.
type StatPoint struct {
	Label  string    `json:"label"`
	Metric string    `json:"metric"`
	Ts     time.Time `json:"ts"`
	Value  float64   `json:"value"`
}

// UpdateSettings defines model for UpdateSettings.
type UpdateSettings struct {
	BlobMaxSize              *int64 `json:"blob_max_size,omitempty"`
	DefaultEvictionThreshold *int64 `json:"default_eviction_threshold,omitempty"`
	MaxFileSize              *int64 `json:"max_file_size,omitempty"`
	WalIdleTimeoutMs         *int64 `json:"wal_idle_timeout_ms,omitempty"`
}

// User defines model for User.
type User struct {
	// BandwidthBps Read bandwidth cap in bytes/sec (0 = unlimited).
	BandwidthBps int64              `json:"bandwidth_bps"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	IsAdmin      bool               `json:"is_admin"`
	Login        string             `json:"login"`

	// QuotaBytes Storage quota in bytes (0 = unlimited).
	QuotaBytes int64 `json:"quota_bytes"`

	// RatePerMin Request rate cap per minute (0 = unlimited).
	RatePerMin int32 `json:"rate_per_min"`
}

// BotId defines model for BotId.
type BotId = openapi_types.UUID

// ChannelId defines model for ChannelId.
type ChannelId = openapi_types.UUID

// TokenId defines model for TokenId.
type TokenId = openapi_types.UUID

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Kind Optional event kind filter.
	Kind *string `form:"kind,omitempty" json:"kind,omitempty"`

	// Limit Maximum number of events to return (default 100).
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of events to skip.
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// QueryStatsParams defines parameters for QueryStats.
type QueryStatsParams struct {
	// Metric The metric name (e.g. storage_bytes, read_bytes).
	Metric string `form:"metric" json:"metric"`

	// Label Optional metric label/dimension.
	Label *string `form:"label,omitempty" json:"label,omitempty"`

	// From Inclusive lower bound of the time window (RFC 3339).
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper bound of the time window (RFC 3339).
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// AddBotJSONRequestBody defines body for AddBot for application/json ContentType.
type AddBotJSONRequestBody = AddBot

// SetBotEnabledJSONRequestBody defines body for SetBotEnabled for application/json ContentType.
type SetBotEnabledJSONRequestBody = SetEnabled

// AddChannelJSONRequestBody defines body for AddChannel for application/json ContentType.
type AddChannelJSONRequestBody = AddChannel

// SetChannelEvictionJSONRequestBody defines body for SetChannelEviction for application/json ContentType.
type SetChannelEvictionJSONRequestBody = SetEviction

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = UpdateSettings

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUser

// SetUserPasswordJSONRequestBody defines body for SetUserPassword for application/json ContentType.
type SetUserPasswordJSONRequestBody = SetPassword

// CreateUserTokenJSONRequestBody defines body for CreateUserToken for application/json ContentType.
type CreateUserTokenJSONRequestBody = CreateToken

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all bots
	// (GET /api/v1/bots)
	ListBots(w http.ResponseWriter, r *http.Request)
	// Add a bot by its Telegram API token
	// (POST /api/v1/bots)
	AddBot(w http.ResponseWriter, r *http.Request)
	// Remove a bot
	// (DELETE /api/v1/bots/{botId})
	DeleteBot(w http.ResponseWriter, r *http.Request, botId BotId)
	// Enable or disable a bot
	// (PUT /api/v1/bots/{botId}/enabled)
	SetBotEnabled(w http.ResponseWriter, r *http.Request, botId BotId)
	// List all channels
	// (GET /api/v1/channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// Add a channel by its bare numeric id
	// (POST /api/v1/channels)
	AddChannel(w http.ResponseWriter, r *http.Request)
	// Decommission a channel
	// (DELETE /api/v1/channels/{channelId})
	DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// Set a channel's eviction threshold
	// (PUT /api/v1/channels/{channelId}/eviction)
	SetChannelEviction(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// List audit/log events
	// (GET /api/v1/events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)
	// Get runtime settings
	// (GET /api/v1/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update runtime settings
	// (PUT /api/v1/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// Query a time-series metric
	// (GET /api/v1/stats)
	QueryStats(w http.ResponseWriter, r *http.Request, params QueryStatsParams)
	// List all users
	// (GET /api/v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Create a new user
	// (POST /api/v1/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Delete a user
	// (DELETE /api/v1/users/{userId})
	DeleteUser(w http.ResponseWriter, r *http.Request, userId UserId)
	// Get a single user
	// (GET /api/v1/users/{userId})
	GetUser(w http.ResponseWriter, r *http.Request, userId UserId)
	// Set a user's password
	// (PUT /api/v1/users/{userId}/password)
	SetUserPassword(w http.ResponseWriter, r *http.Request, userId UserId)
	// List a user's API tokens
	// (GET /api/v1/users/{userId}/tokens)
	ListUserTokens(w http.ResponseWriter, r *http.Request, userId UserId)
	// Create an API token for a user
	// (POST /api/v1/users/{userId}/tokens)
	CreateUserToken(w http.ResponseWriter, r *http.Request, userId UserId)
	// Revoke an API token
	// (DELETE /api/v1/users/{userId}/tokens/{tokenId})
	DeleteUserToken(w http.ResponseWriter, r *http.Request, userId UserId, tokenId TokenId)
	// Liveness probe (public, no auth)
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBots operation middleware
func (siw *ServerInterfaceWrapper) ListBots(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBot operation middleware
func (siw *ServerInterfaceWrapper) AddBot(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBot operation middleware
func (siw *ServerInterfaceWrapper) DeleteBot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "botId" -------------
	var botId BotId

	err = runtime.BindStyledParameterWithOptions("simple", "botId", r.PathValue("botId"), &botId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "botId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBot(w, r, botId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetBotEnabled operation middleware
func (siw *ServerInterfaceWrapper) SetBotEnabled(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "botId" -------------
	var botId BotId

	err = runtime.BindStyledParameterWithOptions("simple", "botId", r.PathValue("botId"), &botId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "botId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetBotEnabled(w, r, botId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddChannel operation middleware
func (siw *ServerInterfaceWrapper) AddChannel(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetChannelEviction operation middleware
func (siw *ServerInterfaceWrapper) SetChannelEviction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetChannelEviction(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, false, "kind", r.URL.Query(), &params.Kind)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryStats operation middleware
func (siw *ServerInterfaceWrapper) QueryStats(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryStatsParams

	// ------------- Required query parameter "metric" -------------

	if paramValue := r.URL.Query().Get("metric"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "metric"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "metric", r.URL.Query(), &params.Metric)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metric", Err: err})
		return
	}

	// ------------- Optional query parameter "label" -------------

	err = runtime.BindQueryParameter("form", true, false, "label", r.URL.Query(), &params.Label)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "label", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) SetUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetUserPassword(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserTokens operation middleware
func (siw *ServerInterfaceWrapper) ListUserTokens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserTokens(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUserToken operation middleware
func (siw *ServerInterfaceWrapper) CreateUserToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUserToken(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserToken operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// ------------- Path parameter "tokenId" -------------
	var tokenId TokenId

	err = runtime.BindStyledParameterWithOptions("simple", "tokenId", r.PathValue("tokenId"), &tokenId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tokenId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserToken(w, r, userId, tokenId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/bots", wrapper.ListBots)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/bots", wrapper.AddBot)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/bots/{botId}", wrapper.DeleteBot)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/bots/{botId}/enabled", wrapper.SetBotEnabled)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/channels", wrapper.ListChannels)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/channels", wrapper.AddChannel)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/channels/{channelId}", wrapper.DeleteChannel)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/channels/{channelId}/eviction", wrapper.SetChannelEviction)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events", wrapper.ListEvents)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/settings", wrapper.GetSettings)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/settings", wrapper.UpdateSettings)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/stats", wrapper.QueryStats)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users", wrapper.ListUsers)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/users", wrapper.CreateUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/users/{userId}", wrapper.DeleteUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users/{userId}", wrapper.GetUser)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/users/{userId}/password", wrapper.SetUserPassword)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users/{userId}/tokens", wrapper.ListUserTokens)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/users/{userId}/tokens", wrapper.CreateUserToken)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/users/{userId}/tokens/{tokenId}", wrapper.DeleteUserToken)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)

	return m
}
